TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

PROD_HOST = p2p


p2p_SRCS += main.cpp
p2p_SRCS += server.cpp
p2p_SRCS += client.cpp
p2p_SRCS += chancache.cpp
p2p_SRCS += channel.cpp

p2p_LIBS += pvAccess pvData Com

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

